name: AntiXrayViewer
version: '${version}'
main: com.example.antixrayviewer.AntiXrayViewer
api-version: '1.21'
authors: [NikitaRTN]
description: AntiXray Viewer plugin for Paper 1.21.4
website: https://github.com/RiseShieldDev/AntiXrayViewer

commands:
  antixrayviewer:
    description: Main command for AntiXrayViewer plugin
    usage: /<command> [help]
    aliases: [axv, antixray]
    permission: antixrayviewer.use
    permission-message: You don't have permission to use this command!

permissions:
  antixrayviewer.*:
    description: Gives access to all AntiXrayViewer commands
    default: op
    children:
      antixrayviewer.use: true
      antixrayviewer.admin: true
      antixrayviewer.reload: true
  
  antixrayviewer.use:
    description: Allows using basic AntiXrayViewer commands
    default: true
  
  antixrayviewer.admin:
    description: Allows using admin AntiXrayViewer commands
    default: op
  
  antixrayviewer.reload:
    description: Allows reloading the plugin configuration
    default: op